export const words = {
  "Anime": [
    "Fullmetal Alchemist",
    "Attack on Titan",
    "Naruto",
    "One Piece",
    "Cowboy Bebop",
    "Demon Slayer",
    "Neon Genesis Evangelion",
    "Jujutsu Kaisen",
    "Nisekoi",
    "Death Note"
  ],
  "Peliculas": [
    "El Padrino",
    "Tiempos Violentos",
    "Matrix",
    "El Origen",
    "Forrest Gump",
    "Volver al Futuro",
    "El Caballero de la Noche",
    "Titanic",
    "Star Wars: Una Nueva Esperanza",
    "Parque Jurásico",
    "El Club de la Pelea",
    "El Señor de los Anillos: La Comunidad del Anillo",
    "El Señor de los Anillos: El Retorno del Rey",
    "Gladiador",
    "Sueños de Libertad",
    "Interestelar",
    "Rescatando al Soldado Ryan",
    "El Silencio de los Inocentes",
    "Avatar",
    "Terminator 2: El Juicio Final",
    "Buenos Muchachos",
    "El Rey León",
    "Toy Story",
    "Corazón Valiente",
    "Alien: El Octavo Pasajero",
    "Tiburón",
    "Rocky",
    "Indiana Jones: En Busca del Arca Perdida",
    "Harry Potter y la Piedra Filosofal",
    "Piratas del Caribe: La Maldición del Perla Negra",
    "Frozen: Una Aventura Congelada",
    "Moana: Un Mar de Aventuras",
    "Aladdín",
    "La Bella y la Bestia",
    "La Sirenita",
    "Mulán",
    "Coco",
    "Buscando a Nemo",
    "Up: Una Aventura de Altura",
    "Toy Story 2",
    "Blancanieves y los Siete Enanitos",
    "Cenicienta",
    "La Bella Durmiente",
    "Bambi",
    "Pinocho",
    "Hércules",
    "Tarzán",
    "Enredados",
    "Ratatouille",
    "Los Increíbles"
  ]
  ,
  "Electrodomesticos": [
    "Refrigerador",
    "Lavadora",
    "Microondas",
    "Licuadora",
    "Aspiradora",
    "Horno eléctrico",
    "Aire acondicionado",
    "Televisor",
    "Secadora",
    "Cafetera"
],
  "Juegos": [
    "The Last of Us Part II",
    "Elden Ring",
    "God of War (2018)",
    "The Legend of Zelda: Breath of the Wild",
    "Minecraft",
    "Fortnite",
    "Among Us",
    "Red Dead Redemption 2",
    "Genshin Impact",
    "Cyberpunk 2077",
    "Grand Theft Auto V",
    "League of Legends",
    "Valorant",
    "Counter-Strike: Global Offensive",
    "Dota 2",
    "Call of Duty: Modern Warfare",
    "FIFA 24",
    "Assassins Creed Valhalla",
    "Dark Souls III",
    "Horizon Zero Dawn",
    "Resident Evil 4",
    "World of Warcraft",
    "The Witcher 3: Wild Hunt",
    "Overwatch",
    "The Elder Scrolls V: Skyrim",
    "Monster Hunter: World",
    "Fall Guys",
    "Apex Legends",
    "Super Mario Odyssey",
    "Halo: Combat Evolved",
    "Resident Evil Village",
    "Bloodborne",
    "Sekiro: Shadows Die Twice",
    "Marvels Spider-Man",
    "Hades",
    "Dead by Daylight",
    "Stardew Valley",
    "Terraria",
    "Pokémon Rojo",
    "Clash Royale"
],
  "Musica": [
    "Guitarra",
    "Batería",
    "Piano",
    "Bajo",
    "Violín",
    "Micrófono",
    "Altavoz",
    "Auriculares",
    "Amplificador",
    "Sintetizador"
  ],
  "Ropa": [
    "Camiseta",
    "Pantalón",
    "Campera",
    "Zapatillas",
    "Sombrero",
    "Bufanda",
    "Guantes",
    "Vestido",
    "Pollera",
    "Shorts"
  ],
  "Deportes": [
    "Fútbol",
    "Baloncesto",
    "Tenis",
    "Natación",
    "Ciclismo",
    "Voleibol",
    "Atletismo",
    "Boxeo",
    "Hockey",
    "Rugby"
  ],
  "ElementosDeportivos":[
    "Pelota",
    "Balón de fútbol",
    "Balón de básquet",
    "Balón de rugby",
    "Raqueta",
    "Raqueta de tenis",
    "Raqueta de ping pong",
    "Palo de hockey",
    "Bate de béisbol",
    "Guante de béisbol",
    "Casco",
    "Rodilleras",
    "Coderas",
    "Canilleras",
    "Arco",
    "Red",
    "Cronómetro",
    "Silbato",
    "Conos",
    "Tabla de surf"
  ],
  "Animales": [
    "Perro",
    "Gato",
    "Caballo",
    "Vaca",
    "Cerdo",
    "Oveja",
    "Cabra",
    "Gallina",
    "Pato",
    "Conejo",
    "León",
    "Tigre",
    "Elefante",
    "Jirafa",
    "Cebra",
    "Mono",
    "Oso",
    "Lobo",
    "Zorro",
    "Ciervo",
    "Delfín",
    "Ballena",
    "Tiburón",
    "Pulpo",
    "Pez",
    "Tortuga",
    "Cocodrilo",
    "Pingüino",
    "Foca",
    "Medusa",
    "Águila",
    "Loro",
    "Paloma",
    "Búho",
    "Flamenco",
    "Mariposa",
    "Abeja",
    "Hormiga",
    "Araña",
    "Serpiente"
  ],
  "Enfermedades": [
    "Gripe",
    "Resfrío",
    "COVID-19",
    "Neumonía",
    "Asma",
    "Diabetes",
    "Hipertensión",
    "Anemia",
    "Obesidad",
    "Cáncer",
    "Migraña",
    "Depresión",
    "Ansiedad",
    "Osteoporosis",
    "Alergia",
    "Gastritis",
    "Úlcera",
    "Hepatitis",
    "VIH/SIDA",
    "Tuberculosis",
    "Dengue",
    "Malaria",
    "Parkinson",
    "Alzheimer",
    "Epilepsia",
    "Varicela"
  ],
  "JugadoresDeFutbol": [
    "Lionel Messi",
    "Cristiano Ronaldo",
    "Diego Maradona",
    "Pelé",
    "Johan Cruyff",
    "Zinedine Zidane",
    "Ronaldinho",
    "Ronaldo Nazário",
    "Neymar",
    "Kylian Mbappé",
    "Erling Haaland",
    "Kevin De Bruyne",
    "Luka Modrić",
    "Xavi Hernández",
    "Andrés Iniesta",
    "Sergio Ramos",
    "Gianluigi Buffon",
    "Iker Casillas",
    "David Beckham",
    "Thierry Henry",
    "Robert Lewandowski",
    "Karim Benzema",
    "Mohamed Salah",
    "Luis Suárez",
    "Antoine Griezmann",
    "Paulo Dybala",
    "Zlatan Ibrahimović",
    "Manuel Neuer",
    "Virgil van Dijk",
    "Ronald Koeman"
  ],
  "Paises": [
    "Argentina",
    "Brasil",
    "Estados Unidos",
    "Canadá",
    "México",
    "España",
    "Francia",
    "Italia",
    "Alemania",
    "Reino Unido",
    "Bolivia",
    "Portugal",
    "Países Bajos",
    "Bélgica",
    "Suiza",
    "Suecia",
    "Noruega",
    "Rusia",
    "China",
    "Japón",
    "Corea del Sur",
    "Corea del norte",
    "India",
    "Australia",
    "Nueva Zelanda",
    "Sudáfrica",
    "Egipto",
    "Marruecos",
    "Nigeria",
    "Chile",
    "Colombia",
    "Perú",
    "Venezuela",
    "Paraguay"
  ],
  "Herramientas": [
    "Martillo",
    "Destornillador",
    "Llave inglesa",
    "Llave francesa",
    "Llave Allen",
    "Alicate",
    "Pinza",
    "Serrucho",
    "Sierra",
    "Cúter",
    "Taladro",
    "Broca",
    "Nivel",
    "Cinta métrica",
    "Metro",
    "Lima",
    "Formón",
    "Prensa",
    "Pala",
    "Cincel"
  ]
}