export enum AppErrorCode{
    ROOM_NOT_FOUND = "ROOM NOT FOUND",
    GAME_NOT_FOUND = "GAME NOT FOUND",
    PLAYER_NOT_FOUND = "PLAYER NOT FOUND",
    PLAYER_CANT_PLAY = "PLAYER CANT PLAY",
    USER_NOT_FOUND = "USER NOT FOUND",
    USER_EXISTS = "USER ALREADY EXISTS",
    ROOM_NOT_CREATED = "UNABLE TO CREATE ROOM",
    INCORRECT_PASSWORD = "INCORRECT PASSWORD"
}